### ISSUE TITLE
Sign In button - not appearing even though the server is available

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/TodoList-iOS#12]

**Comment by jesspittman** [comment]
Sign in button appears and says Try again if it failed to connect to DB. It doesnt actually try again when pushed though. 

So what needs to be done right now is changing the action that runs when the button is clicked to instead of just performing the segue, it needs to check if its connected. If it was connected, performSegue, else, try to connect again (and then performSegue?)

**Comment by jesspittman** [comment]
Button can now try again.  Possible improvements:

- Segue to next page if try again succeeds. Right now you have to click the button after it changes to "Sign in".
- Disable the button while connecting.
- Animation spinner while it is trying to connect.

**Comment by jesspittman** [comment]
Ok. Button is disabled while it tries to connect. Might want to add some disabled theme color to portray that?
